Class {
	#name : #CTDfsWalkerData,
	#superclass : #Object,
	#instVars : [
		'descriptor',
		'level',
		'parent',
		'labelsWidth',
		'boxesWidth',
		'rows',
		'object',
		'shape'
	],
	#category : #'Containers-Essentials-Outliner-Walkers'
}

{ #category : #accessing }
CTDfsWalkerData >> boxesWidth [

	^ boxesWidth
]

{ #category : #accessing }
CTDfsWalkerData >> boxesWidth: anObject [

	boxesWidth := anObject
]

{ #category : #accessing }
CTDfsWalkerData >> descriptor [

	^ descriptor
]

{ #category : #accessing }
CTDfsWalkerData >> descriptor: anObject [

	descriptor := anObject
]

{ #category : #accessing }
CTDfsWalkerData >> labelsWidth [

	^ labelsWidth
]

{ #category : #accessing }
CTDfsWalkerData >> labelsWidth: anObject [

	labelsWidth := anObject
]

{ #category : #accessing }
CTDfsWalkerData >> level [

	^ level
]

{ #category : #accessing }
CTDfsWalkerData >> level: anObject [

	level := anObject
]

{ #category : #accessing }
CTDfsWalkerData >> object [

	^ object
]

{ #category : #accessing }
CTDfsWalkerData >> object: anObject [

	object := anObject
]

{ #category : #accessing }
CTDfsWalkerData >> parent [

	^ parent
]

{ #category : #accessing }
CTDfsWalkerData >> parent: anObject [

	parent := anObject
]

{ #category : #accessing }
CTDfsWalkerData >> rows [

	^ rows
]

{ #category : #accessing }
CTDfsWalkerData >> rows: anObject [

	rows := anObject
]

{ #category : #accessing }
CTDfsWalkerData >> shape [

	^ shape
]

{ #category : #accessing }
CTDfsWalkerData >> shape: anObject [

	shape := anObject
]
